sudo: required
services:
  - docker

before_install:
  - docker build -t pbegle/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run pbegle/react-test npm test -- --coverage

after_success:
  - docker build -t pbegle/multi-client ./client
  - docker build -t pbegle/multi-nginx ./nginx
  - docker build -t pbegle/multi-server ./server
  - docker build -t pbegle/multi-worker ./worker
  # - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker login -u pbegle -p $DOCKER_PASSWORD
  - docker push pbegle/multi-client
  - docker push pbegle/multi-nginx
  - docker push pbegle/multi-server
  - docker push pbegle/multi-worker
  