sudo: required
services:
  - docker

before_install:
  - docker build -t pbegle/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run pbegle/react-test npm test -- --coverage

after_success:
  - docker build -t pbegle/multi-client ./client
  - docker build -t pbegle/multi-nginx ./nginx
  - docker build -t pbegle/multi-server ./server
  - docker build -t pbegle/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push pbegle/multi-client
  - docker push pbegle/multi-nginx
  - docker push pbegle/multi-server
  - docker push pbegle/multi-worker
  
deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-west-2-083108554360
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY